<center>


# *Matematicas Para Ciencia de Datos*
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="150">
</p>


Daniel Eduardo Vázquez Espinoza


</center>

In [2]:
import numpy as np
from numpy.random import randn
from matplotlib import pyplot
import matplotlib.pyplot as plt
from IPython import display
from sklearn.preprocessing import StandardScaler
import pandas as pd
import plotly.express as px

A diferencia del ejemplo, se generaro X como una matriz polinomal lineal de coheficientes aleatorios. 

In [3]:
# Dimensiones
n = 1000
# Generamos X
import random

X = random.sample(range(1,10),1) * randn(n) + random.sample(range(1,10),1)
#ax+b


In [4]:
float_formatter = "{:.4f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [5]:
#Calculamos sus medidas de tendecia central y dispercion
X_column = np.resize(X,(n,1))
scaler = StandardScaler()
X_std = scaler.fit_transform(X_column)
print('media X_std = ',np.mean(X_std).round(5))
print('desviación estándar X_std = ',np.std(X_std).round(5))
print('varianza X_std = ',np.var(X_std).round(5))

media X_std =  -0.0
desviación estándar X_std =  1.0
varianza X_std =  1.0


Para obtener Y lo obtendremos igual al ejemplo en funcion de X



In [6]:
Y =  X  + 3.5 * randn(n)

In [7]:
Y_column = np.resize(Y,(n,1))
scaler = StandardScaler()
Y_std = scaler.fit_transform(Y_column)
print('media Y_std = ',np.mean(Y_std).round(5))
print('desviación estándar Y_std = ',np.std(Y_std).round(5))
print('varianza Y_std = ',np.var(Y_std).round(5))

media Y_std =  0.0
desviación estándar Y_std =  1.0
varianza Y_std =  1.0


In [8]:
# Dataframe A
A = pd.DataFrame()
A[['col_1']]= pd.DataFrame(X)
A[['col_2']]= pd.DataFrame(Y)
# Dataframe A_std
A_std = pd.DataFrame()
A_std[['col_1']]= pd.DataFrame(X_std)
A_std[['col_2']]= pd.DataFrame(Y_std)
# Dataframe A_centered
A_centered = pd.DataFrame()
A_centered[['col_1']]= pd.DataFrame(X) - pd.DataFrame(X).mean()
A_centered[['col_2']]= pd.DataFrame(Y) - pd.DataFrame(Y).mean()

In [9]:
import plotly.graph_objects as go
fig_1 = px.scatter(A, x="col_1", y="col_2",
                  opacity=0.3,
                   color_discrete_sequence=['blueviolet']
                  )
fig_2 = px.scatter(A_std, x="col_1", y="col_2", 
                    opacity=0.6,
                   color_discrete_sequence=['orange']
                   )
fig_3 = px.scatter(A_centered, x="col_1", y="col_2", 
                   opacity=0.3,
                   color_discrete_sequence=['gray']
                   )
fig = go.Figure(data=fig_1.data + fig_2.data + fig_3.data )
#fig = go.Figure(data=fig_2.data  )
fig.show()
#fig.write_image("data_std_centered.pdf", width=900, height=600)

En esta sección se realizara una comparacion de la matriz covarancia con el calculo de $A_{std}^T$$A_{std}$

In [10]:
Matriz_covarianza = A_std.cov()
Matriz_covarianza

col_1     col_2
col_1  1.001001  0.819786
col_2  0.819786  1.001001

In [11]:
from numpy.linalg import eig
auto_valores, auto_vectores = eig(Matriz_covarianza)
print('Autovalores de la matriz de covarianza de A_std = \n', auto_valores)
print('Autovectores de la matriz de covarianza de A_std = \n', auto_vectores)

Autovalores de la matriz de covarianza de A_std = 
 [1.8208 0.1812]
Autovectores de la matriz de covarianza de A_std = 
 [[0.7071 -0.7071]
 [0.7071 0.7071]]


In [12]:
## auto_valor[1] corresponde a auto_valor[0]
auto_valores[1] * auto_vectores[0] - Matriz_covarianza.dot(auto_vectores[0])

col_1   -1.387779e-16
col_2    2.775558e-17
dtype: float64

In [13]:
## auto_valor[0] corresponde a auto_valor[1]
auto_valores[0] * auto_vectores[1] - Matriz_covarianza.dot(auto_vectores[1])

col_1   -2.220446e-16
col_2   -2.220446e-16
dtype: float64

In [14]:
fig = px.scatter(A_std,
                 x="col_1", 
                 y="col_2", 
                 color_discrete_sequence=['orange'], 
                 marginal_x='violin', 
                 marginal_y='violin',
                 opacity=0.6
                )


arrow_1 = go.layout.Annotation(dict(
                x=  auto_valores[1] * auto_vectores[0][0], ## auto_valor[1] corresponde a auto_valor[0]
                y=  auto_valores[1] * auto_vectores[0][1],
                xref="x", yref="y",
                text="",
                showarrow=True,
                axref = "x", ayref='y',
                ax= 0,
                ay= 0,
                arrowhead = 3,
                arrowwidth=2.5,
                arrowcolor=' mediumseagreen',)
            )

arrow_2 = go.layout.Annotation(dict(
                x=  auto_valores[0] * auto_vectores[1][0], ## auto_valor[0] corresponde a auto_valor[1]
                y=  auto_valores[0] * auto_vectores[1][1],
                xref="x", yref="y",
                text="",
                showarrow=True,
                axref = "x", ayref='y',
                ax= 0,
                ay= 0,
                arrowhead = 3,
                arrowwidth=2.5,
                arrowcolor='blueviolet',)
            )


fig.update_layout(annotations= [arrow_1,arrow_2])
fig.show()
#fig.write_image("figura_matriz_covarianza.pdf", width=900, height=600)

Veamos:

$corr(x,y) = \frac{{\rm cov(x,y)}}{{\rm std}(x){\rm std}(y)}=\frac{\langle x_{std}, y_{std} \rangle}{n-1}$

In [15]:
S = A_std.T.dot(A_std) ### La matriz de covarianza es S/(n-1)
S

col_1        col_2
col_1  1000.000000   818.965831
col_2   818.965831  1000.000000

In [16]:
auto_valores, auto_vectores = eig(S)
print(auto_valores)
print(auto_vectores)

[1818.9658 181.0342]
[[0.7071 -0.7071]
 [0.7071 0.7071]]


In [17]:
print('singular_value_1 =', np.sqrt(auto_valores[0]).round(4))
print('singular_value_2 =', np.sqrt(auto_valores[1]).round(4))

singular_value_1 = 42.6493
singular_value_2 = 13.4549


Creación de componentes principales a través de SVD

componente_principal_1 = $σ_1u_1$(column vector)

componente_principal_2 = $σ_2u_2$(column vector)

In [18]:
from scipy.linalg import svdvals
print('Valores singulares A_std = ',svdvals(A_std))

Valores singulares A_std =  [42.6493 13.4549]


In [19]:
from scipy import linalg
U, S, Vt = linalg.svd(A_std, full_matrices=False)

In [20]:
U.shape, S.shape, Vt.shape

((1000, 2), (2,), (2, 2))

In [21]:
print('Valores singulares de A_std = ', S)

Valores singulares de A_std =  [42.6493 13.4549]


In [22]:
Matriz_U = pd.DataFrame(U)
Matriz_Vt = pd.DataFrame(Vt)

In [23]:
print('componente_principal_1 =\n ', S[0]*Matriz_U[0])
print('componente_principal_2 =\n ', S[1]*Matriz_U[1])

componente_principal_1 =
  0     -1.705496
1      0.916299
2      2.429771
3      1.366258
4      0.300822
         ...   
995    1.063354
996    0.870338
997    0.031707
998    0.083791
999    1.739867
Name: 0, Length: 1000, dtype: float64
componente_principal_2 =
  0     -0.517725
1      0.087692
2      0.792979
3      0.121713
4      0.293854
         ...   
995   -0.202527
996   -0.123609
997   -0.143099
998    0.498997
999    0.325891
Name: 1, Length: 1000, dtype: float64


row_vector_1 = 
$σ_
1
v_
1$

row_vector_ 2 = 
$σ_2
v_
2$

In [24]:
Matriz_U.describe().round(6)

0            1
count  1000.000000  1000.000000
mean      0.000000     0.000000
std       0.031639     0.031639
min      -0.117249    -0.103909
25%      -0.020836    -0.021690
50%       0.001153    -0.001091
75%       0.021311     0.021071
max       0.086049     0.103915

In [25]:
Matriz_Vt.T.describe().round(6)

0         1
count  2.000000  2.000000
mean  -0.707107  0.000000
std    0.000000  1.000000
min   -0.707107 -0.707107
25%   -0.707107 -0.353553
50%   -0.707107  0.000000
75%   -0.707107  0.353553
max   -0.707107  0.707107

PCA

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(A_std)
principalDf = pd.DataFrame(data = principalComponents
             ,columns = ['componente_principal_1', 'componente_principal_2'])

In [27]:
principalDf

componente_principal_1  componente_principal_2
0                  1.705496               -0.517725
1                 -0.916299                0.087692
2                 -2.429771                0.792979
3                 -1.366258                0.121713
4                 -0.300822                0.293854
..                      ...                     ...
995               -1.063354               -0.202527
996               -0.870338               -0.123609
997               -0.031707               -0.143099
998               -0.083791                0.498997
999               -1.739867                0.325891

[1000 rows x 2 columns]

En lo cual tenemos que es lo mismo.

In [28]:
principalDf.describe().round(2)

componente_principal_1  componente_principal_2
count                 1000.00                 1000.00
mean                    -0.00                    0.00
std                      1.35                    0.43
min                     -3.67                   -1.40
25%                     -0.91                   -0.29
50%                     -0.05                   -0.01
75%                      0.89                    0.28
max                      5.00                    1.40

Se prueba que:

$std(\sigma_i u_i) = \frac{\sigma_i}{\sqrt{n-1}}$

In [29]:
print('std de la componente 1', S[0]/np.sqrt(n-1))  
print('std de la componente 2', S[1]/np.sqrt(n-1))  

std de la componente 1 1.3493652647973982
std de la componente 2 0.42569400296486337


Grafica de la primera componente.

In [30]:
principalDf['cero_column'] = 0
fig = px.scatter(principalDf,
                 x='componente_principal_1', 
                 y='cero_column', 
                 color_discrete_sequence=['blueviolet'], 
                 opacity=0.3
                )
fig.update_xaxes(ticks='outside', 
                 tickwidth=1, 
                 tickcolor='gray', 
                 ticklen=5)
fig.update_xaxes(showgrid=False)
fig.update_yaxes(
    scaleanchor = 'x',
    constrain='domain'
)
fig.update_layout(yaxis={'visible': False, 'showticklabels': False})
fig.update_traces(mode = 'markers', 
                  hovertemplate = None
)
fig.update_layout(hovermode='x unified')
fig.update_traces(
    hovertemplate =' ',
    showlegend = False,
)
fig.update_layout(
    hoverlabel = dict(
        bgcolor = 'LightSteelBlue',
        font_size = 40,
    )
)
fig.show()
#fig.write_image('componente_1.pdf', width=900, height=600)

Grafica:
$$A_1 = \sigma_1 u_1 v_1^T$$

In [31]:
A_1 = pd.DataFrame()
A_1[['col_1']]= pd.DataFrame(Vt[0][0] * principalDf['componente_principal_1'])
A_1[['col_2']]= pd.DataFrame(Vt[0][1] * principalDf['componente_principal_1'])

In [32]:
import plotly.graph_objects as go
fig_1 = px.scatter(A_1, x="col_1", y="col_2",
                  opacity=0.3,
                   color_discrete_sequence=['blueviolet']
                  )
fig_2 = px.scatter(A_std, x="col_1", y="col_2", 
                    opacity=0.6,
                   color_discrete_sequence=['orange']
                   )
fig = go.Figure(data=fig_1.data + fig_2.data)
fig.show()
#fig.write_image("A_1.pdf", width=900, height=600)

$$A = \sigma_1 u_1 v_1^T +  \sigma_2 u_2 v_2^T$$

In [33]:
principalDf['col_1'] = principalDf['componente_principal_2']  ## cambio de nombre de columnas para poder sumar
principalDf['col_2'] = principalDf['componente_principal_2'] 
A_2 = pd.DataFrame()
A_2[['col_1']]= A_1[['col_1']].add(pd.DataFrame(Vt[1][0] * principalDf['col_1']))
A_2[['col_2']]= A_1[['col_2']].add(pd.DataFrame(Vt[1][1] * principalDf['col_2']))
import plotly.graph_objects as go
fig_1 = px.scatter(A_2, x="col_1", y="col_2",
                  opacity=0.3,
                   color_discrete_sequence=['blueviolet']
                  )
fig_2 = px.scatter(A_std, x="col_1", y="col_2", 
                    opacity=0.3,
                   color_discrete_sequence=['orange']
                   )
fig = go.Figure(data=fig_1.data + fig_2.data)
fig.show()

*Varianza explicada y varianza total*


Cada valor singular explica una parte de la varianza total:
$$T=\frac{\sigma_1^2+\sigma_2^2}{n-1}$$

In [34]:
pca.explained_variance_

array([1.8208, 0.1812])

In [35]:
varianza_explicada_1 = (S[0]*S[0]/(n-1)).round(4)
varianza_explicada_2 = (S[1]*S[1]/(n-1)).round(4)
print('varianza_explicada_1 = ',varianza_explicada_1)
print('varianza_explicada_2 = ',varianza_explicada_2)

varianza_explicada_1 =  1.8208
varianza_explicada_2 =  0.1812


In [36]:
pca.explained_variance_ratio_ 

array([0.9095, 0.0905])

Radio Varianza explicada

* radio_varianza_explicada_1 = $\frac{\sigma_1^2}{\sigma_1^2+\sigma_2^2}$
* radio_varianza_explicada_2 = $\frac{\sigma_2^2}{\sigma_1^2+\sigma_2^2}$



In [37]:
radio_varianza_explicada_1 = (S[0]*S[0]/(S[0]*S[0]+S[1]*S[1])).round(4)
radio_varianza_explicada_2 = (S[1]*S[1]/(S[0]*S[0]+S[1]*S[1])).round(4)
print('radio_varianza_explicada_1 = ', radio_varianza_explicada_1)
print('radio-varianza_explicada_2 = ', radio_varianza_explicada_2)

radio_varianza_explicada_1 =  0.9095
radio-varianza_explicada_2 =  0.0905


In [39]:
!pip install nbconvert

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [41]:
!jupyter nbconvert --to html DanielVazquez_Ejercicio.ipynb

[NbConvertApp] Converting notebook DanielVazquez_Ejercicio.ipynb to pdf
/usr/local/lib/python3.8/dist-packages/nbconvert/filters/datatypefilter.py:39: UserWarning: Your element with mimetype(s) dict_keys(['text/html']) is not able to be represented.
  warn("Your element with mimetype(s) {mimetypes}"
/usr/local/lib/python3.8/dist-packages/nbconvert/filters/datatypefilter.py:39: UserWarning: Your element with mimetype(s) dict_keys(['text/html']) is not able to be represented.
  warn("Your element with mimetype(s) {mimetypes}"
/usr/local/lib/python3.8/dist-packages/nbconvert/filters/datatypefilter.py:39: UserWarning: Your element with mimetype(s) dict_keys(['text/html']) is not able to be represented.
  warn("Your element with mimetype(s) {mimetypes}"
/usr/local/lib/python3.8/dist-packages/nbconvert/filters/datatypefilter.py:39: UserWarning: Your element with mimetype(s) dict_keys(['text/html']) is not able to be represented.
  warn("Your element with mimetype(s) {mimetypes}"
/usr/local/l